export interface DemoCase {
  id: string;
  title: string;
  orpha_code: number;
  description: string;
  expected_diagnosis: string;
  teaching_point: string;
  modalities: ("notes" | "photo" | "lab" | "vcf")[];
  hpo_terms: { hpo_id: string; label: string; confidence: number; source: string }[];
  patient: { age: string; sex: "male" | "female" };
  confidence_expected: number;
}

export const DEMO_CASES: DemoCase[] = [
  {
    id: "dravet-syndrome",
    title: "Dravet syndrome",
    orpha_code: 34587,
    description: "6-month-old male infant presenting with prolonged febrile seizures and developmental plateau after routine vaccination",
    expected_diagnosis: "Dravet syndrome",
    teaching_point: "SCN1A loss-of-function variants cause sodium channelopathy; fever-provoked prolonged hemiclonic seizures in the first year of life are a cardinal feature.",
    modalities: ["notes", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0002373", label: "Febrile seizures", confidence: 0.95, source: "notes" },
      { hpo_id: "HP:0001250", label: "Seizures", confidence: 0.92, source: "notes" },
      { hpo_id: "HP:0001263", label: "Global developmental delay", confidence: 0.80, source: "notes" },
      { hpo_id: "HP:0010819", label: "Atonic seizures", confidence: 0.75, source: "notes" },
    ],
    patient: { age: "6 months", sex: "male" },
    confidence_expected: 82,
  },
  {
    id: "marfan-syndrome",
    title: "Marfan syndrome",
    orpha_code: 558,
    description: "16-year-old male referred for tall stature, scoliosis, and incidental aortic root dilatation on echocardiogram",
    expected_diagnosis: "Marfan syndrome",
    teaching_point: "FBN1 variants disrupt fibrillin-1, causing connective tissue fragility; aortic root aneurysm with lens dislocation and skeletal features fulfils Ghent criteria.",
    modalities: ["notes", "photo", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0001519", label: "Disproportionate tall stature", confidence: 0.90, source: "notes" },
      { hpo_id: "HP:0000316", label: "Hypertelorism", confidence: 0.72, source: "photo" },
      { hpo_id: "HP:0001083", label: "Ectopia lentis", confidence: 0.88, source: "notes" },
      { hpo_id: "HP:0002616", label: "Aortic root aneurysm", confidence: 0.93, source: "notes" },
    ],
    patient: { age: "16 years", sex: "male" },
    confidence_expected: 88,
  },
  {
    id: "gaucher-type1",
    title: "Gaucher disease type 1",
    orpha_code: 77259,
    description: "42-year-old female with progressive splenomegaly, fatigue, and thrombocytopenia of unknown aetiology",
    expected_diagnosis: "Gaucher disease type 1",
    teaching_point: "Biallelic GBA variants reduce glucocerebrosidase activity; bone marrow infiltration by lipid-laden macrophages explains cytopenias and organomegaly.",
    modalities: ["notes", "lab"],
    hpo_terms: [
      { hpo_id: "HP:0001903", label: "Anaemia", confidence: 0.85, source: "lab" },
      { hpo_id: "HP:0001744", label: "Splenomegaly", confidence: 0.95, source: "notes" },
      { hpo_id: "HP:0002240", label: "Hepatomegaly", confidence: 0.80, source: "notes" },
      { hpo_id: "HP:0100512", label: "Low glucocerebrosidase activity", confidence: 0.90, source: "lab" },
    ],
    patient: { age: "42 years", sex: "female" },
    confidence_expected: 85,
  },
  {
    id: "phenylketonuria",
    title: "Phenylketonuria",
    orpha_code: 716,
    description: "3-week-old female with elevated phenylalanine on newborn dried blood spot screen, fair hair and eczema",
    expected_diagnosis: "Phenylketonuria",
    teaching_point: "PAH deficiency impairs phenylalanine hydroxylation; untreated hyperphenylalaninaemia is neurotoxic, but early dietary intervention prevents intellectual disability.",
    modalities: ["notes", "lab", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0001249", label: "Intellectual disability", confidence: 0.78, source: "notes" },
      { hpo_id: "HP:0000729", label: "Autistic behaviour", confidence: 0.70, source: "notes" },
      { hpo_id: "HP:0001047", label: "Atopic eczema", confidence: 0.82, source: "photo" },
      { hpo_id: "HP:0011968", label: "Feeding difficulties", confidence: 0.75, source: "notes" },
    ],
    patient: { age: "3 weeks", sex: "female" },
    confidence_expected: 78,
  },
  {
    id: "turner-syndrome",
    title: "Turner syndrome",
    orpha_code: 881,
    description: "14-year-old female with short stature, primary amenorrhoea, and incidental horseshoe kidney on renal ultrasound",
    expected_diagnosis: "Turner syndrome",
    teaching_point: "45,X monosomy causes ovarian dysgenesis and short stature; cardiac (coarctation, bicuspid aortic valve) and renal anomalies are common co-occurrences requiring surveillance.",
    modalities: ["notes", "lab", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0004322", label: "Short stature", confidence: 0.92, source: "notes" },
      { hpo_id: "HP:0000047", label: "Horseshoe kidney", confidence: 0.78, source: "notes" },
      { hpo_id: "HP:0001629", label: "Ventricular septal defect", confidence: 0.70, source: "notes" },
      { hpo_id: "HP:0000851", label: "Conductive hearing impairment", confidence: 0.68, source: "notes" },
    ],
    patient: { age: "14 years", sex: "female" },
    confidence_expected: 75,
  },
  {
    id: "rett-syndrome",
    title: "Rett syndrome",
    orpha_code: 778,
    description: "2-year-old female with normal early development followed by loss of purposeful hand use, stereotypic hand-wringing, and acquired microcephaly",
    expected_diagnosis: "Rett syndrome",
    teaching_point: "MECP2 variants cause X-linked neurodevelopmental regression almost exclusively in females; the hallmark is purposeful hand use loss with stereotypic wringing movements after 6–18 months of normal development.",
    modalities: ["notes", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0002333", label: "Motor regression", confidence: 0.93, source: "notes" },
      { hpo_id: "HP:0000733", label: "Stereotypy", confidence: 0.95, source: "notes" },
      { hpo_id: "HP:0002360", label: "Sleep disturbance", confidence: 0.77, source: "notes" },
      { hpo_id: "HP:0001276", label: "Hypertonia", confidence: 0.72, source: "notes" },
    ],
    patient: { age: "2 years", sex: "female" },
    confidence_expected: 87,
  },
  {
    id: "neurofibromatosis-type1",
    title: "Neurofibromatosis type 1",
    orpha_code: 636,
    description: "8-year-old male with six café-au-lait macules greater than 5 mm, axillary freckling, and a palpable plexiform neurofibroma along the left arm",
    expected_diagnosis: "Neurofibromatosis type 1",
    teaching_point: "NF1 loss-of-function activates RAS/MAPK signalling; diagnosis requires two or more NIH criteria, and plexiform neurofibromas carry risk of malignant peripheral nerve sheath tumour transformation.",
    modalities: ["notes", "photo", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0000957", label: "Café-au-lait spots", confidence: 0.95, source: "photo" },
      { hpo_id: "HP:0009732", label: "Plexiform neurofibroma", confidence: 0.88, source: "notes" },
      { hpo_id: "HP:0009736", label: "Tibial pseudarthrosis", confidence: 0.65, source: "notes" },
      { hpo_id: "HP:0000407", label: "Sensorineural hearing impairment", confidence: 0.70, source: "notes" },
    ],
    patient: { age: "8 years", sex: "male" },
    confidence_expected: 83,
  },
  {
    id: "duchenne-muscular-dystrophy",
    title: "Duchenne muscular dystrophy",
    orpha_code: 98896,
    description: "5-year-old male with progressive proximal muscle weakness, Gowers sign, calf pseudohypertrophy, and markedly elevated creatine kinase",
    expected_diagnosis: "Duchenne muscular dystrophy",
    teaching_point: "Out-of-frame DMD deletions abolish dystrophin, causing early-onset severe myopathy; creatine kinase is typically 50–100× upper limit of normal at presentation.",
    modalities: ["notes", "lab", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0003236", label: "Elevated serum creatine kinase", confidence: 0.95, source: "lab" },
      { hpo_id: "HP:0001324", label: "Muscle weakness", confidence: 0.92, source: "notes" },
      { hpo_id: "HP:0003701", label: "Proximal muscle weakness", confidence: 0.90, source: "notes" },
      { hpo_id: "HP:0003325", label: "Limb-girdle muscle weakness", confidence: 0.85, source: "notes" },
    ],
    patient: { age: "5 years", sex: "male" },
    confidence_expected: 90,
  },
  {
    id: "pompe-disease",
    title: "Pompe disease",
    orpha_code: 365,
    description: "4-month-old male with hypertrophic cardiomyopathy, generalised hypotonia, poor feeding, and markedly reduced acid alpha-glucosidase activity on dried blood spot",
    expected_diagnosis: "Pompe disease",
    teaching_point: "GAA variants impair lysosomal glycogen degradation; classic infantile Pompe presents with cardiomegaly and hypotonia, and enzyme replacement therapy is life-saving if started early.",
    modalities: ["notes", "lab", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0001639", label: "Hypertrophic cardiomyopathy", confidence: 0.93, source: "notes" },
      { hpo_id: "HP:0003236", label: "Elevated serum creatine kinase", confidence: 0.82, source: "lab" },
      { hpo_id: "HP:0001263", label: "Global developmental delay", confidence: 0.78, source: "notes" },
      { hpo_id: "HP:0002194", label: "Delayed motor development", confidence: 0.80, source: "notes" },
    ],
    patient: { age: "4 months", sex: "male" },
    confidence_expected: 80,
  },
  {
    id: "williams-syndrome",
    title: "Williams syndrome",
    orpha_code: 904,
    description: "3-year-old female with supravalvular aortic stenosis, elfin facies, hypercalcaemia, hypersocial behaviour, and mild intellectual disability",
    expected_diagnosis: "Williams syndrome",
    teaching_point: "7q11.23 microdeletion including ELN causes Williams syndrome; the characteristic hypersociability combined with supravalvular aortic stenosis and hypercalcaemia is pathognomonic.",
    modalities: ["notes", "photo", "lab", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0001629", label: "Ventricular septal defect", confidence: 0.80, source: "notes" },
      { hpo_id: "HP:0001263", label: "Global developmental delay", confidence: 0.85, source: "notes" },
      { hpo_id: "HP:0000316", label: "Hypertelorism", confidence: 0.75, source: "photo" },
      { hpo_id: "HP:0000219", label: "Thin vermilion border", confidence: 0.78, source: "photo" },
    ],
    patient: { age: "3 years", sex: "female" },
    confidence_expected: 72,
  },
  {
    id: "fabry-disease",
    title: "Fabry disease",
    orpha_code: 324,
    description: "22-year-old male with episodic burning acroparesthesia triggered by heat, exercise-induced pain crises, angiokeratomas, and haematuria",
    expected_diagnosis: "Fabry disease",
    teaching_point: "GLA variants reduce alpha-galactosidase A activity causing lysosomal globotriaosylceramide accumulation; young males with unexplained acroparesthesia, angiokeratomas, and renal/cardiac involvement should be screened.",
    modalities: ["notes", "photo", "lab"],
    hpo_terms: [
      { hpo_id: "HP:0002719", label: "Recurrent infections", confidence: 0.65, source: "notes" },
      { hpo_id: "HP:0001654", label: "Abnormal heart valve morphology", confidence: 0.73, source: "notes" },
      { hpo_id: "HP:0000790", label: "Haematuria", confidence: 0.87, source: "lab" },
      { hpo_id: "HP:0003056", label: "Acroparesthesia", confidence: 0.92, source: "notes" },
    ],
    patient: { age: "22 years", sex: "male" },
    confidence_expected: 76,
  },
  {
    id: "cystic-fibrosis",
    title: "Cystic fibrosis",
    orpha_code: 586,
    description: "7-year-old female with chronic productive cough, recurrent Pseudomonas pneumonia, failure to thrive, and elevated sweat chloride of 98 mmol/L",
    expected_diagnosis: "Cystic fibrosis",
    teaching_point: "Biallelic CFTR variants cause defective chloride transport; elevated sweat chloride (>60 mmol/L) remains the gold-standard diagnostic test, and CFTR modulators now offer disease-modifying treatment for many variants.",
    modalities: ["notes", "lab", "vcf"],
    hpo_terms: [
      { hpo_id: "HP:0006528", label: "Recurrent pneumonia", confidence: 0.93, source: "notes" },
      { hpo_id: "HP:0002099", label: "Asthma", confidence: 0.70, source: "notes" },
      { hpo_id: "HP:0001508", label: "Failure to thrive", confidence: 0.88, source: "notes" },
      { hpo_id: "HP:0000508", label: "Ptosis", confidence: 0.60, source: "notes" },
    ],
    patient: { age: "7 years", sex: "female" },
    confidence_expected: 92,
  },
];
